### PR TITLE
basic A and B rotational support

### PR DESCRIPTION
**Pull request by paukstelis**
Basic functionality for A and B axes. Settings enable jog and status. Messages may need another couple of conditions (A, no B; B, no A) but maybe there is a more clever way to do it.

### CODE REVIEW

**Comment by synman** [comment]
I'm out of town for a couple days.  Will get on this once back home mid next week.

**Review by synman — CHANGES_REQUESTED** [review]
Let's keep .vscode metadata out of the repo.

**Comment by synman** [comment]
I'm going to merge this and clean up the .vscode stuff

**Comment by paukstelis** [comment]
Weird, it should have been in .gitignore...

**Comment by synman** [comment]
nbd... looks like I've got some post merge cleanup to do.  my devel machine is not happy.

Screenshot 2023-01-05 at 7 55 27 PM

**Comment by synman** [comment]
Error instantiating bettergrblsupportViewModel : TypeError: self.settings.hasA is not a function
    at new BettergrblsupportViewModel (http://octopi-laser/static/webassets/packed_plugins.js?1b3c85b6:430:35)
    at _createViewModelInstance (http://octopi-laser/static/webassets/packed_core.js?d44a1aa2:1117:213)
    at HTMLDocument.<anonymous> (http://octopi-laser/static/webassets/packed_core.js?d44a1aa2:1121:45)
    at e (http://octopi-laser/static/webassets/packed_libs.js?7111420c:13:30005)
    at t (http://octopi-laser/static/webassets/packed_libs.js?7111420c:13:30307)
(anonymous) @ packed_core.js?d44a1aa2:1122
packed_core.js?d44a1aa2:1131

**Comment by synman** [comment]
weird.. this may be an nfs sync issue on my end.

**Comment by paukstelis** [comment]
That was stuff I was messing with after PR submission. I did not realize that would get pulled along. I was trying to figure out how to add the origin_axes conditionally based on the settings.

**Comment by synman** [comment]
I'll take care of this... but yeah, everything you do in the PR branch amends the PR.  I'm still not sure we have an actual problem.  I see these settings defined in __init__.py

**Comment by synman** [comment]
ah... yeah, it's broke.

should be: 

self.settings.settings.plugins.bettergrblsupport.hasA and self.settings.settings.plugins.bettergrblsupport.hasB

**Comment by paukstelis** [comment]
> ah... yeah, it's broke.
> 
> should be:
> 
> self.settings.settings.plugins.bettergrblsupport.hasA and self.settings.settings.plugins.bettergrblsupport.hasB

I tried that, still didn't work for me.

**Comment by synman** [comment]
it's because the view model isn't fully built in its constructor.   settings gets wired up right before onBeforeBinding.

All better now.  I have no way to test this as I don't have 5 axes machine, but it's binding properly now.

https://github.com/synman/Octoprint-Bettergrblsupport/commit/41640fe3aa538133aec696e0789b85dee7b65586

**Comment by synman** [comment]
ok, maybe I can test a little.   I love the look here

Screenshot 2023-01-05 at 8 13 32 PM

**Comment by synman** [comment]
Screenshot 2023-01-05 at 8 16 26 PM
I think we can do this a little more cleanly.   Pretty sure there is a way to push within a list in js.  I'm even tempted to push them to index 0... they way they'd show up before Z.

**Comment by synman** [comment]
hmm... do we even need them?   It doesn't look like they are tied to setting or traveling to an origin.  Selecting "A" and hitting home, generated the following GCODE:

Send: G0 G90 X0 Y0 Z0

I half expected to see "G0 G90 A0"

you can find this logic here: https://github.com/synman/Octoprint-Bettergrblsupport/blob/devel/octoprint_bettergrblsupport/__init__.py#L1341

**Comment by synman** [comment]
It gets set on the other side here:  https://github.com/synman/Octoprint-Bettergrblsupport/blob/devel/octoprint_bettergrblsupport/__init__.py#L1425

**Comment by synman** [comment]
Once you have it squared away, feel free to submit another PR.  Let's get A/B cleaned up in the axes bar too.  I think they'll look best to the left of Z.

**Pull request merged**
