### PR TITLE
add a and b to origin_axis

### PR DESCRIPTION
**Pull request by paukstelis**
Adds A and B axes for individual origin and as part of ALL.
Fixes/improves message response.

### CODE REVIEW

**Comment by synman** [comment]
are you reusing the same branch as the last PR?   It's best to delete the branch used in a PR and always start fresh with a synced new branch when starting a new one.   I'm not sure how git will like trying to do a merge with previously squashed commits returning.

**Comment by paukstelis** [comment]
ahh...i did sync, but did not delete first. I am not all that well versed in git usage.

**Comment by synman** [comment]
perhaps you can merge this branch into your local DEVEL branch in your fork.  verify all the stuff you want is there then you can close this PR and nuke the branch. 

Then when you think you are 100% ready to deliver, initiate a PR with a new feature branch of your choosing.  This is the way :)

**Comment by paukstelis** [comment]
Seems like there is some complications because of how I initiated the fork. devel is my default branch, which I can't delete. I can rename it, but I am not sure that will get me where I want to go. I might just have to wipe and re-fork.

**Comment by synman** [comment]
Okay, that actually makes sense.  You were working directly in DEVEL and doing a PR from it.  I did a traditional PR the other day while testing out a VS Code Pull Request / Issues extension.  This is a great example of how a PR should come in:

https://github.com/synman/Octoprint-Bettergrblsupport/pull/106

**Pull request closed without merging**
